#!/bin/bash
clear
NC='\e[0m'
grenbo="\e[92;1m"

# // IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
clear

# SlowDns
NS=$( cat /etc/xray/dns )
PUB=$( cat /etc/slowdns/server.pub )

# // Telegram Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
# // izin Ip
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear


# // Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)

data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/ALAWI-VPN/autoscript/main/REGISTRASI"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281524266702"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit 0
  fi
}
checking_sc
clear
export TIME="10"
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
clear
  echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
  echo -e "             CREATE SSH / OPENVPN ACCOUNT      "
  echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
  echo -e ""
  echo -e ""  
read -p " Username : " Login
read -p " Password : " Pass
read -p " Limit IP : " iplimit
read -p " Expired (Days) : " masaaktif
#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
fi
echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
clear

cat > /var/www/html/ssh-$Login.txt <<-END
◇━━━━━━━━━━━━━━━━━◇
Format SSH OVPN Account
◇━━━━━━━━━━━━━━━━━◇
Username         : $Login
Password         : $Pass
◇━━━━━━━━━━━━━━━━━◇
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH UDP     : 1-65535
Port SSH WS      : 80, 8080, 8081-9999
Port SSH SSL WS  : 443
Port SSL/TLS     : 400-900
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 1194
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
◇━━━━━━━━━━━━━━━━━◇
SSH UDP VIRAL : $domain:1-65535@$Login:$Pass
◇━━━━━━━━━━━━━━━━━◇
HTTP COSTUM : $domain:80@$Login:$Pass
◇━━━━━━━━━━━━━━━━━◇
Payload WSS: GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
◇━━━━━━━━━━━━━━━━━◇
OVPN Download : https://$domain:81/
◇━━━━━━━━━━━━━━━━━◇
Dibuat Pada      : $tnggl
Berakhir Pada    : $expe
◇━━━━━━━━━━━━━━━━━◇

END

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</code>
<code>Succes Cretae SSH Ovpn Account    </code>
<code>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</code>
<code>Username         : </code> <code>$Login</code>
<code>Password         : </code> <code>$Pass</code>
<code>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</code>
<code>Host             : </code> <code>$domain</code>
<code>Port OpenSSH     : 443, 80, 22</code>
<code>Port Dropbear    : 443, 109</code>
<code>Port SSH WS      : 80, 8080, 8081-9999 </code>
<code>Port SSH UDP     : 1-65535 </code>
<code>Port SSH SSL WS  : 443</code>
<code>Port SSL/TLS     : 400-900</code>
<code>Port OVPN WS SSL : 443</code>
<code>Port OVPN SSL    : 443</code>
<code>Port OVPN TCP    : 443, 1194</code>
<code>Port OVPN UDP    : 2200</code>
<code>BadVPN UDP       : 7100, 7300, 7300</code>
<code>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</code>
<code>SSH UDP VIRAL : </code><code>$domain:1-65535@$Login:$Pass
<code>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</code>
<code>HTTP COSTUM : </code><code>$domain:80@$Login:$Pass</code>
<code>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</code>
<code>Payload WSS      : </code><code>GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]</code>
<code>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</code>
OVPN Download : https://$domain:81/
<code>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</code>
<code>Save Link Account: </code>https://$domain:81/ssh-$Login.txt
<code>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</code>
Dibuat Pada          : $tnggl
Berakhir Pada        : $expe
<code>◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
echo ""
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log
echo -e "         SSH / OPENVPN ACCOUNT   " | tee -a /etc/user-create/user.log
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log
echo -e "Username         : $Login" | tee -a /etc/user-create/user.log
echo -e "Password         : $Pass" | tee -a /etc/user-create/user.log
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log
echo -e "Limit Ip         : ${iplimit} User" | tee -a /etc/user-create/user.log
echo -e "Host             : $domain" | tee -a /etc/user-create/user.log
echo -e "Location         : $CITY" | tee -a /etc/user-create/user.log
echo -e "Port OpenSSH     : 443, 80, 22" | tee -a /etc/user-create/user.log
echo -e "Port DNS         : 443, 53 ,22 " | tee -a /etc/user-create/user.log
echo -e "Port SSH UDP     : 1-65535" | tee -a /etc/user-create/user.log
echo -e "Port Dropbear    : 443, 109" | tee -a /etc/user-create/user.log
echo -e "Port SSH WS      : 80, 8080, 8880, 2082, 2095" | tee -a /etc/user-create/user.log
echo -e "Port SSH SSL WS  : 443" | tee -a /etc/user-create/user.log
echo -e "Port SSL/TLS     : 400-900" | tee -a /etc/user-create/user.log
echo -e "Port OVPN WS SSL : 443" | tee -a /etc/user-create/user.log
echo -e "Port OVPN SSL    : 443" | tee -a /etc/user-create/user.log
echo -e "Port OVPN TCP    : 443, 1194" | tee -a /etc/user-create/user.log
echo -e "Port OVPN UDP    : 2200" | tee -a /etc/user-create/user.log
echo -e "BadVPN UDP       : 7100, 7300, 7300" | tee -a /etc/user-create/user.log
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log
echo -e "SSH UDP VIRAL : $domain:1-65535@$Login:$Pass"            | tee -a /etc/user-create/user.log
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log
echo -e "HTTP COSTUM : $domain:80@$Login:$Pass"                   | tee -a /etc/user-create/user.log
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log
echo -e "Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]" | tee -a /etc/user-create/user.log
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log
echo -e "Payload WS       : GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: ws[crlf][crlf]" | tee -a /etc/user-create/user.log
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log
echo -e "OVPN Download    : https://$domain:81/" | tee -a /etc/user-create/user.log
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log
echo -e "Save Link Account: https://$domain:81/ssh-$Login.txt" | tee -a /etc/user-create/user.log
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log
echo -e "Dibuat Pada      : $tnggl" | tee -a /etc/user-create/user.log
echo -e "Berakhir Pada    : $expe" | tee -a /etc/user-create/user.log
echo -e "_______________________________________________________" | tee -a /etc/user-create/user.log

read -p "Enter Back To Menu"
menu
