#!/bin/bash
# // color
grs="\033[1;93m"
bg="\033[42m"
gr="\e[92;1m"
NC='\033[0m'
clear
echo -e "${grs}┌────────────────────────────────────────────────────┐${NC}"
echo -e "${grs}│${bg}                   MENU MANAGER SSH                 ${NC}${grs}│${NC}"
echo -e "${grs}└────────────────────────────────────────────────────┘${NC}"
echo -e "${grs}┌─────────────────────────┐┌─────────────────────────┐${NC}"
echo -e "${grs}│ [${gr}01${NC}] • ADD AKUN         ${grs}││ [${gr}06${NC}] • USER CONFIG      ${grs}│${NC}"
echo -e "${grs}│                         ││                         │${NC}"
echo -e "${grs}│ [${gr}02${NC}] • TRIAL AKUN       ${grs}││ [${gr}07${NC}] • LOCK USER        ${grs}│${NC}"
echo -e "${grs}│                         ││                         │${NC}"
echo -e "${grs}│ [${gr}03${NC}] • RENEW AKUN       ${grs}││ [${gr}08${NC}] • SET TIME LOCK    ${grs}│${NC}"
echo -e "${grs}│                         ││                         │${NC}"
echo -e "${grs}│ [${gr}04${NC}] • DELETE AKUN      ${grs}││ [${gr}09${NC}] • UNLOCK AKUN      ${grs}│${NC}"
echo -e "${grs}│                         ││                         │${NC}"
echo -e "${grs}│ [${gr}05${NC}] • USER ONLINE      ${grs}││ [${gr}00${NC}] • BACK TO MENU     ${grs}│${NC}"
echo -e "${grs}└─────────────────────────┘└─────────────────────────┘${NC}"
echo -e ""
read -p "$(echo -e "Select From Options [ ${gr}1${NC} - ${gr}9${NC} or ${gr}0${NC} ] : ")" menu
echo -e ""
case $menu in
1|01)
    addssh
    ;;
2|02)
    trial
    ;;
3|03)
    renewssh
    ;;
4|04)
    delssh
    ;;
5|05)
    cekssh
    ;;
6|06)
    clear
    user-ssh
    ;;
7|07)
    clear
    lock
    ;;
8|08)
    autokill
    ;;
9|09)
    clear
    unlock
    ;;
0|00)
    menu
    ;;
*)
    menu
    ;;
esac

