#!/bin/bash
# // Bima | PROJECT
# // p
# // t.me/bimavpn1 >> Telegram
# // Dean >> Fb

# // color
grenbo="\e[92;1m"
NC='\033[0m'
clear
echo -e "\033[1;93m┌─────────────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│$NC\033[42m          MENU MANAGER SSH                     $NC"
echo -e "\033[1;93m└─────────────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌─────────────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│ $NC  ${WH}[\033[0m01${WH}]${NC} ${COLOR1}• ${WH}ADD AKUN${NC}      ${WH}[${COLOR1}05${WH}]${NC} ${COLOR1}• ${WH}CEK USER ONLINE${NC}   $COLOR1 $NC"
echo -e "\033[1;93m│ $NC                                              ${NC} $COLOR1 $NC"
echo -e "\033[1;93m│ $NC  ${WH}[\033[0m02${WH}]${NC} ${COLOR1}• ${WH}TRIAL AKUN${NC}    ${WH}[${COLOR1}06${WH}]${NC} ${COLOR1}• ${WH}CEK USER CONFIG${NC}    $COLOR1 $NC"
echo -e "\033[1;93m│ $NC                                              ${NC} $COLOR1 $NC"
echo -e "\033[1;93m│ $NC  ${WH}[\033[0m03${WH}]${NC} ${COLOR1}• ${WH}RENEW AKUN${NC}    ${WH}[${COLOR1}07${WH}]${NC} ${COLOR1}• ${WH}LOCK USER MELANGGAR ${NC}    $COLOR1 $NC"
echo -e "\033[1;93m│ $NC                                              ${NC} $COLOR1 $NC"
echo -e "\033[1;93m│ $NC  ${WH}[\033[0m04${WH}]${NC} ${COLOR1}• ${WH}DELETE AKUN${NC}   ${WH}[${COLOR1}08${WH}]${NC} ${COLOR1}• ${WH}SETTING TIME AND LOCK LOGIN${NC}    $COLOR1 $NC"
echo -e "\033[1;93m│ $NC                                              ${NC} $COLOR1 $NC"
echo -e "\033[1;93m│ $NC  ${WH}[\033[0m00${WH}]${NC} ${COLOR1}• ${WH}GO BACK${NC}       ${WH}[${COLOR1}09${WH}]${NC} ${COLOR1}• ${WH}UNLOCK USER MULTI LOGIN${NC}    $COLOR1 $NC"
echo -e "\033[1;93m└─────────────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 10 or 0 ] : " menu
echo -e ""
case $menu in
1)
    addssh
    ;;
2)
    trial
    ;;
3)
    renewssh
    ;;
4)
    delssh
    ;;
5)
    cekssh
    ;;
6)
    clear
    user-ssh
    ;;
7)
    clear
    lock
    ;;
8)
    autokill
    ;;
9)
    clear
    unlock
    ;;
10) 
    clear
    lock
   ;;
11)
    clear
    unlock
    ;;
12)
    clear
    user-ssh
    ;;
*)
    menu
    ;;
esac

