#!/bin/bash

# // color
grs="\033[1;93m"
bg="\033[42m"
gr="\e[92;1m"
NC='\033[0m'
clear

echo -e ""
echo -e "${grs}┌─────────────────────────────────────────────────┐${NC}"
echo -e "${grs}│${bg}               MENU MANAGER SYSTEM               ${NC}${grs}│${NC}"
echo -e "${grs}└─────────────────────────────────────────────────┘${NC}"
echo -e "${grs}┌───────────────────────┐ ┌───────────────────────┐${NC}"
echo -e "${grs}│ [${gr}01${NC}] • CHANGE DOMAIN  ${grs}│ │ [${gr}05${NC}] • CREATE SLOWDNS ${grs}│${NC}"
echo -e "${grs}│                       │ │                   ${NC}    │${NC}"
echo -e "${grs}│ [${gr}02${NC}] • CHANGE BANNER  ${grs}│ │ [${gr}06${NC}] • RUNNING SERVICE${grs}│${NC}"
echo -e "${grs}│                       │ │                       │${NC}"
echo -e "${grs}│ [${gr}03${NC}] • FIX CERTIFICATE${grs}│ │ [${gr}07${NC}] • SPEEDTEST      ${grs}│${NC}"
echo -e "${grs}│                       │ │                       │${NC}"
echo -e "${grs}│ [${gr}04${NC}] • CLEAR CACHE    ${grs}│ │ [${gr}08${NC}] • CHECK BANDWIDTH${grs}│${NC}"
echo -e "${grs}└───────────────────────┘ └───────────────────────┘${NC}"
echo -e "${grs}┌─────────────────────────────────────────────────┐${NC}"
echo -e "${grs}│                [${gr}00${NC}] BACK TO MENU                ${grs}│${NC}"
echo -e "${grs}└─────────────────────────────────────────────────┘${NC}"
echo -e ""
read -p "$(echo -e "Select From Options [ ${gr}1${NC} - ${gr}8${NC} or ${gr}0${NC} ] : ")" menu
echo -e ""
case $menu in
1) clear ;
    addhost
    ;;
2) clear ;
    nano /etc/kyt.txt
    ;;
3) clear ;
    fixcert
    ;;
4) clear ;
    clearcache
    ;;
5) clear ;
    sd
    ;;
6) clear ;
   run
   ;;
7) clear ;
  speedtest
  ;;
8) clear ;
    bw
    ;;
*)
    menu
    ;;
esac
