#!/bin/bash

# // Bimavpn | PROJECT
# // Telegram
# // Dean >> Fb

# // color
grenbo="\e[92;1m"
NC='\033[0m'


echo -e "\033[1;93m┌─────────────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│$NC\033[42m          MENU MANAGER VMESS                     $NC"
echo -e "\033[1;93m└─────────────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌─────────────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│ $NC  ${WH}[\033[0m01${WH}]${NC} ${COLOR1}• ${WH}ADD AKUN${NC}      ${WH}[\033[0m04${WH}]${NC} ${COLOR1}• ${WH}DELETE AKUN${NC} "
echo -e "\033[1;93m│ $NC                                              ${NC} $COLOR1 $NC"
echo -e "\033[1;93m│ $NC  ${WH}[\033[0m02${WH}]${NC} ${COLOR1}• ${WH}TRIAL AKUN${NC}    ${WH}[${COLOR1}05${WH}]${NC} ${COLOR1}• ${WH}CEK USER ONLINE${NC}   $COLOR1 $NC"
echo -e "\033[1;93m│ $NC                                              ${NC} $COLOR1 $NC"
echo -e "\033[1;93m│ $NC  ${WH}[\033[0m03${WH}]${NC} ${COLOR1}• ${WH}RENEW AKUN${NC}    ${WH}[${COLOR1}06${WH}]${NC} ${COLOR1}• ${WH}CEK USER CONFIG${NC}    $COLOR1 $NC"
echo -e "\033[1;93m└─────────────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 6 or 0 ] : " menu
echo -e ""
case $menu in
1)   clear ;
    addws
    ;;
2) clear ;
    trialws
    ;;
3) clear ;
    renewws
    ;;
4) clear ;
    delws
    ;;
5) clear ;
    cekws
    ;;
6) clear ;
    user-ws
   ;;
*) clear ;
    menu
    ;;
esac
