#!/bin/bash
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m>"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m Sukses !\033[1;37m"
    tput cnorm
}

pointing() {
# Mengambil tanggal sekarang
current_date=$(date +"%Y-%m-%d")
# warna
cyan='\033[1;36m'
green='\e[1;32m'
NC='\e[0m'
clear
echo -e ""
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e "  \e[1;97;101m            ADD IP IZIN SCRIPT            ${NC}"
echo -e "  \e[1;97;101m            CODE BY: ALAWI-VPN            ${NC}"
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""

while true; do
read -rp "  Masukkan username : " user
    if [ -z "$user" ]; then     echo ""
    else
        break
    fi
done
while true; do
read -rp "  Expired SC (hari) : " tgl
    if [ -z "$tgl" ]; then echo ""
    else
        break
    fi
done
while true; do
read -rp "  Masukkan IP VPS   : " ip
    if [ -z "$ip" ]; then echo ""
    else
        break
    fi
done
tanggal=$(date -d "$current_date +${tgl} days" +"%Y-%m-%d")
echo  "### ${user} ${tanggal} ${ip}" >> REGISTRASI
}
giting() {
git add REGISTRASI
git commit -m "perbarui ip"
git push
}
pointing
echo -e ""
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e "  \e[1;97;101m              UPDATE IP IZIN              \e[0m"
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""
echo -e "  \033[1;91mUpdate IP IZIN SCRIPT\033[1;37m"
fun_bar 'giting'
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""
read -n 1 -s -r -p "  Press [ Enter ] to back on menu"
