#!/bin/bash
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m Sukses !\033[1;37m"
    tput cnorm
}

pointing() {
# Mengambil tanggal sekarang
current_date=$(date +"%Y-%m-%d")
# warna
cyan='\033[1;36m'
green='\e[1;32m'
NC='\e[0m'
clear
echo -e ""
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e "  \e[1;97;101m            ADD IP IZIN SCRIPT            ${NC}"
echo -e "  \e[1;97;101m            CODE BY: sosohrajeh            ${NC}"
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""

while true; do
read -rp "  Masukkan username : " user
    if [ -z "$user" ]; then     echo ""
    else
        break
    fi
done
while true; do
read -rp "  Expired SC (hari) : " tgl
    if [ -z "$tgl" ]; then echo ""
    else
        break
    fi
done
while true; do
read -rp "  Masukkan IP VPS   : " ip
    if [ -z "$ip" ]; then echo ""
    else
        break
    fi
done
tanggal=$(date -d "$current_date +${tgl} days" +"%Y-%m-%d")
echo  "### ${user} ${tanggal} ${ip}" >> izin
}
giting() {
git add izin
git commit -m "perbarui ip"
git push
}
# function bot notif 
function notiftelebot() {
export CHATID="6331389328"
export KEY="7097156228:AAF4Qav6b_8ag9iaKwhdIF1E9tOpSDiQUzI"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
export user="${user}"
export tanggal="${tanggal}"
export ip="${ip}"

python3 - <<END
import os
import requests
# Mendapatkan nilai variabel bash menggunakan os.getenv()
CHATID = os.getenv('CHATID')
KEY = os.getenv('KEY')
TIME = os.getenv('TIME')
URL = os.getenv('URL')
user = os.getenv('user')
tanggal = os.getenv('tanggal')
ip = os.getenv('ip')

# Fungsi untuk mengirim pesan ke bot Telegram
def kirim_pesan(pesan):
    TOKEN = KEY  # Ganti dengan token API bot Telegram Anda
    chat_id = CHATID  # Ganti dengan ID obrolan atau username penerima pesan

    url = f'https://api.telegram.org/bot{TOKEN}/sendMessage'
    params = {
        'chat_id': chat_id,
        'text': pesan,
        'parse_mode': 'HTML'  # Menggunakan HTML untuk formatting teks
    }

    response = requests.post(url, params=params)
    return response.json()
#proses kirim teks/pesan ken bot
pesan = f"""
━━━━━━━━━━━━━━━━━━━━━
<b>IZIN SCRIPT sosohrajeh PREM</b>
━━━━━━━━━━━━━━━━━━━━━
<code>Username   :</code> <code>{user}</code>
<code>IP VPS     :</code> <code>{ip}</code>
<code>Exp SCRIPT :</code> <code>{tanggal}</code>
━━━━━━━━━━━━━━━━━━━━━
➣ <b>REPOSITORY INDONESIA</b>
<code>wget https://raw.githubusercontent.com/sosohrajeh/repoindo/main/repoid && chmod +x repoid && screen -S update bash repoid</code>

➣ <b>CMD INSTALL SCRIPT:</b>
<code>apt install -y && wget -q https://raw.githubusercontent.com/sosohrajeh/nyaman/main/setup.sh && chmod +x setup.sh && screen -S alawi bash setup.sh</code>

➣ <b>Jika terjadi lost signal ketik saja</b> <code>screen -r update</code> <b>atau</b> <code>screen -r alawi</code>
"""
kirim_pesan(pesan)
END
}

pointing
echo -e ""
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e "  \e[1;97;101m              UPDATE IP IZIN              \e[0m"
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""
echo -e "  \033[1;91mUpdate IP IZIN SCRIPT\033[1;37m"
fun_bar 'giting'
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""
notiftelebot
read -n 1 -s -r -p "  Press [ Enter ] to back on menu"
menu
