#!/bin/bash
# warna
bg="\e[1;97;101m"
cyan='\033[1;36m'
green='\e[1;32m'
NC='\e[0m'
clear
# functions
update() {
    git add bangkalan
    git commit -m "bangkalanip"
    git push
}

# tambah bangkalan ip
tambah() {
pointing() {
# Mengambil tanggal sekarang
current_date=$(date +"%Y-%m-%d")
# warna
cyan='\033[1;36m'
green='\e[1;32m'
NC='\e[0m'
clear
echo -e ""
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e "  \e[1;97;101m            ADD IP IZIN SCRIPT            ${NC}"
echo -e "  \e[1;97;101m            CODE BY: ALAWI VPN            ${NC}"
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""

while true; do
    read -rp "  Masukkan username : " user
    [[ -n "$user" ]] && break
done
while true; do
    read -rp "  Expired SC (hari) : " tgl
    [[ -n "$tgl" ]] && break
done
while true; do
    read -rp "  Masukkan IP VPS   : " ip
    [[ -n "$ip" ]] && break
done
tanggal=$(date -d "$current_date +${tgl} days" +"%Y-%m-%d")
echo  "### ${user} ${tanggal} ${ip}" >> bangkalan
}
# function bot notif
notiftelebot() {
export CHATID="6331389328"
export KEY="7097156228:AAF4Qav6b_8ag9iaKwhdIF1E9tOpSDiQUzI"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
export user="${user}"
export tanggal="${tanggal}"
export ip="${ip}"

python3 - <<END
import os
import requests
# Mendapatkan nilai variabel bash menggunakan os.getenv()
CHATID = os.getenv('CHATID')
KEY = os.getenv('KEY')
TIME = os.getenv('TIME')
URL = os.getenv('URL')
user = os.getenv('user')
tanggal = os.getenv('tanggal')
ip = os.getenv('ip')

# Fungsi untuk mengirim pesan ke bot Telegram
def kirim_pesan(pesan):
    TOKEN = KEY  # Ganti dengan token API bot Telegram Anda
    chat_id = CHATID  # Ganti dengan ID obrolan atau username penerima pesan

    url = f'https://api.telegram.org/bot{TOKEN}/sendMessage'
    params = {
        'chat_id': chat_id,
        'text': pesan,
        'parse_mode': 'HTML'  # Menggunakan HTML untuk formatting teks
}

    response = requests.post(url, params=params)
    return response.json()
#proses kirim teks/pesan ken bot
pesan = f"""
━━━━━━━━━━━━━━━━━━━━━
<b>IZIN SCRIPT ALAWI VPN PREM</b>
━━━━━━━━━━━━━━━━━━━━━
<code>Username   :</code> <code>{user}</code>
<code>IP VPS     :</code> <code>{ip}</code>
<code>Exp SCRIPT :</code> <code>{tanggal}</code>
━━━━━━━━━━━━━━━━━━━━━
➣ <b>REPOSITORY INDONESIA</b>
<code>wget https://raw.githubusercontent.com/petapan/maknyos/main/repoid && chmod +x repoid && screen -S update bash repoid</code>

➣ <b>CMD INSTALL SCRIPT:</b>
<code>apt install -y && wget -q https://raw.githubusercontent.com/petapan/labang/main/setup.sh && chmod +x setup.sh && screen -S alawi bash setup.sh</code>

➣ <b>Jika terjadi lost signal ketik saja</b> <code>screen -r update</code> <b>atau</b> <code>screen -r alawi</code>
"""
kirim_pesan(pesan)
END
}
pointing
notiftelebot
}
# perbarui bangkalan ip
# warna
cyan='\033[1;36m'
green='\e[1;32m'
NC='\e[0m'
perbarui() {
hasil_penemuan() {
mapfile -t lines < bangkalan
found=0
tgl_lama=""
wkwk=""
for (( i=0; i<${#lines[@]}; i++ )); do
    line="${lines[$i]}"
    # Mengekstrak nama, tanggal, dan IP dari baris
    name=$(echo "$line" | awk '{print $2}')
    date_lama=$(echo "$line" | awk '{print $3}')
    ip_lama=$(echo "$line" | awk '{print $4}')
    if [[ "$ip_lama" == "$ip" ]]; then
        wkwk=$(date -d "$date_lama + 0 days" +%Y-%m-%d)
        found=1
        tgl_lama=$date_lama
        break
    fi
done
echo -e ""
echo -e "  ${green}### $name $wkwk $ip_lama${NC}"
echo -e ""
}

# Membaca IP dari pengguna
bg="\e[1;97;101m"
echo -e ""
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e "  ${bg}            MENU RENEW IZIN IP            ${NC}"
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""
while true; do
    read -p "  Masukkan IP: " ip
    [[ -n "$ip" ]] && break
done
hasil_penemuan

while true; do
    read -p "  Masukkan jumlah hari tambahan: " days
    [[ -n "$days" ]] && break
done
# Menyimpan konten file ke dalam array
mapfile -t lines < bangkalan

# Menandai apakah IP ditemukan atau tidak
found=0
old_date=""
new_date=""

# Loop melalui setiap baris dalam array
for (( i=0; i<${#lines[@]}; i++ )); do
    line="${lines[$i]}"
    # Mengekstrak nama, tanggal, dan IP dari baris
    name=$(echo "$line" | awk '{print $2}')
    current_date=$(echo "$line" | awk '{print $3}')
    current_ip=$(echo "$line" | awk '{print $4}')

    # Memeriksa apakah IP cocok dengan IP yang diberikan
    if [[ "$current_ip" == "$ip" ]]; then
        # Mengubah tanggal dengan menambahkan jumlah hari
        new_date=$(date -d "$current_date + $days days" +%Y-%m-%d)
        # Mengganti tanggal pada baris
        lines[$i]="${lines[$i]/$current_date/$new_date}"
        found=1
        old_date=$current_date
        break
    fi
done

# Menulis kembali konten yang telah diubah ke file
printf "%s\n" "${lines[@]}" > bangkalan

if [[ $found -eq 1 ]]; then
    echo -e "  Tanggal berhasil diubah untuk IP ${green}$ip.${NC}"
    echo -e "  Tanggal lama: ${green}$old_date${NC}"
    echo -e "  Tanggal baru: ${green}$new_date${NC}"
else
    echo -e "  IP ${green}$ip tidak ditemukan dalam file.${NC}"
fi
}

kurangi() {
hasil_penemuan() {
# warna
cyan='\033[1;36m'
green='\e[1;32m'
NC='\e[0m'
mapfile -t lines < bangkalan
found=0
tgl_lama=""
wkwk=""
for (( i=0; i<${#lines[@]}; i++ )); do
    line="${lines[$i]}"
    # Mengekstrak nama, tanggal, dan IP dari baris
    name=$(echo "$line" | awk '{print $2}')
    date_lama=$(echo "$line" | awk '{print $3}')
    ip_lama=$(echo "$line" | awk '{print $4}')
    if [[ "$ip_lama" == "$ip" ]]; then
        wkwk=$(date -d "$date_lama + 0 days" +%Y-%m-%d)
        found=1
        tgl_lama=$date_lama
        break
    fi
done
echo -e ""
echo -e "  ${green}### $name $wkwk $ip_lama${NC}"
echo -e ""
}

# Membaca IP dari pengguna
echo -e ""
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e "  ${bg}        MENU KURANGI WAKTU IZIN IP        ${NC}"
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""
while true; do
    read -p "  Masukkan IP: " ip
    [[ -n "$ip" ]] && break
done
hasil_penemuan
while true; do
    read -p "  Masukkan jumlah hari pengurangan: " days
    [[ -n "$days" ]] && break
done
# Menyimpan konten file ke dalam array
mapfile -t lines < bangkalan

# Menandai apakah IP ditemukan atau tidak
found=0
old_date=""
new_date=""

# Loop melalui setiap baris dalam array
for (( i=0; i<${#lines[@]}; i++ )); do
    line="${lines[$i]}"
    # Mengekstrak nama, tanggal, dan IP dari baris
    name=$(echo "$line" | awk '{print $2}')
    current_date=$(echo "$line" | awk '{print $3}')
    current_ip=$(echo "$line" | awk '{print $4}')

    # Memeriksa apakah IP cocok dengan IP yang diberikan
    if [[ "$current_ip" == "$ip" ]]; then
        # Mengubah tanggal dengan menambahkan jumlah hari
        new_date=$(date -d "$current_date - $days days" +%Y-%m-%d)
        # Mengganti tanggal pada baris
        lines[$i]="${lines[$i]/$current_date/$new_date}"
        found=1
        old_date=$current_date
        break
    fi
done

# Menulis kembali konten yang telah diubah ke file
printf "%s\n" "${lines[@]}" > bangkalan

if [[ $found -eq 1 ]]; then
    echo -e "  Tanggal berhasil diubah untuk IP ${green}$ip.${NC}"
    echo -e "  Tanggal lama: ${green}$old_date${NC}"
    echo -e "  Tanggal baru: ${green}$new_date${NC}"
else
    echo -e " IP ${green}$ip tidak ditemukan dalam file.${NC}"
fi
}

hapus() {
# bismillah bisa buat
# variable
file=bangkalan

# perintah masukan
echo -e ""
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e "  ${bg}     MENU DELETE IZIN IP BY: ALAWIVPN     ${NC}"
echo -e "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | lolcat
echo -e ""
while true; do
    read -rp "  Masukkan ip: " ip
    [[ -n "$ip" ]] && break
done
echo -e ""

# proses deleting
sed -i "/$ip/d" $file
echo -e "  Ip ${green}$ip berhasil dihapus${NC}"
}

# menu

clear
# Warna ANSI
light_cyan="\e[96m"
reset_color="\e[0m"
blue_bg="\e[44m"
white="\e[97m"
bold='\033[1m'
YELLOW='\033[0;33m'

# Menentukan lebar layar
screen_width=$(tput cols)

# Menampilkan garis pembungkus
printf "${light_cyan}"
printf '%*s\n' "${screen_width}" '' | tr ' ' '-'

# Menampilkan judul
title="MENU SETTING IZIN IP"
title_length=${#title}
padding_length=$(( (screen_width - title_length) / 2 ))

padding=""
for ((i=0; i<padding_length; i++)); do
    padding+=" "
done

printf "${blue_bg}${bold}${white}%s%s%s%s${reset_color}\n" "$padding" "$title" "$padding"

# Menampilkan garis pembungkus
printf "${light_cyan}"
printf '%*s\n' "${screen_width}" '' | tr ' ' '-'
printf "${reset_color}\n"
cyan='\033[1;36m'
green='\e[1;32m'
NC='\e[0m'

echo -e " [${cyan}01${NC}] Tambah bangkalan ip"
echo -e " [${cyan}02${NC}] Perbarui bangkalan ip"
echo -e " [${cyan}03${NC}] Kurangi bangkalan ip"
echo -e " [${cyan}04${NC}] Hapus bangkalan ip"
echo -e " [${cyan}05${NC}] Update Github"
echo -e " [${cyan}00${NC}] Keluar"
echo -e ""
read -rp "$(echo -e " Silahkan pilih ${green}1${NC}-${green}4 ${NC}atau ${green}0${NC}: ")" jwb
case $jwb in
    1 | 01) clear ; tambah ; update ;;
    2 | 02) clear ; perbarui ; update ;;
    3 | 03) clear ; kurangi ; update ;;
    4 | 04) clear ; hapus ; update ;;
    5 | 05) update ;;
    0 | 00) clear ; exit ;;
    *) clear ; bash news ;;
esac
