#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
NS=$( cat /etc/xray/dns )
PUB=$( cat /etc/slowdns/server.pub )
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting notif
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"

# getting notif trx
CHATID2=$(grep -E "^#bot# " "/etc/bottrx/.bot.db" | cut -d ' ' -f 3)
KEY2=$(grep -E "^#bot# " "/etc/bottrx/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL2="https://api.telegram.org/bot$KEY2/sendMessage"
clear

# detail server
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
clear
# // color
grs="\033[1;93m"
bg="\033[42m"
gr="\e[92;1m"
NC='\033[0m'
clear
echo -e ""
echo -e "${grs}┌───────────────────────────────────────────────┐${NC}"
echo -e "${grs}│${bg}                 ADD ACCOUNT SSH               ${NC}${grs}│${NC}"
echo -e "${grs}└───────────────────────────────────────────────┘${NC}"
echo -e ""
read -p " Username : " Login
read -p " Password : " Pass
read -p " Limit IP : " iplimit
read -p " Exp Days : " masaaktif
read -p " Pembeli  : " pembeli
#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
fi
echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
clear

cat > /var/www/html/ssh-$Login.txt <<-END
◇━━━━━━━━━━━━━━━━━◇
Format SSH OVPN Account
◇━━━━━━━━━━━━━━━━━◇
Username         : $Login
Password         : $Pass
◇━━━━━━━━━━━━━━━━━◇
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH UDP     : 1-65535
Port SSH WS      : 80, 8080, 8081-9999
Port SSH SSL WS  : 443
Port SSL/TLS     : 400-900
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 1194
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
◇━━━━━━━━━━━━━━━━━◇
SSH UDP VIRAL : $domain:1-65535@$Login:$Pass
◇━━━━━━━━━━━━━━━━━◇
HTTP COSTUM : $domain:80@$Login:$Pass
◇━━━━━━━━━━━━━━━━━◇
Payload WSS: GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
◇━━━━━━━━━━━━━━━━━◇
OVPN Download : https://$domain:81/
◇━━━━━━━━━━━━━━━━━◇
Dibuat Pada      : $tnggl
Berakhir Pada    : $expe
◇━━━━━━━━━━━━━━━━━◇
END

# Function to send notification to Telegram Bot
function notiftelebot() {
    sleep 0
    CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>    Succes Create SSH Ovpn Account</b>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<code>Username    :</code> <code>$Login</code>
<code>Password    :</code> <code>$Pass</code>
<code>Host        :</code> <code>$domain</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>                   INFORMASI PORT</b>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<code>OpenSSH     :</code> 443, 80, 22
<code>Dropbear    :</code> 443, 109
<code>SSH WS      :</code> 80, 8080, 8081-9999
<code>SSH UDP     :</code> 1-65535
<code>SSH SSL WS  :</code> 443
<code>SSL/TLS     :</code> 400-900
<code>OVPN WS SSL :</code> 443
<code>OVPN SSL    :</code> 443
<code>OVPN TCP    :</code> 443, 1194
<code>OVPN UDP    :</code> 2200
<code>BadVPN UDP  :</code> 7100, 7300, 7300
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>SSH UDP :</b>
<code>$domain:1-65535@$Login:$Pass</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>HTTP CUSTOM :</b>
<code>$domain:80@$Login:$Pass</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>Payload WSS :</b>
<code>GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>OVPN Download:</b>
https://$domain:81/
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>Save Link Account:</b>
https://$domain:81/ssh-$Login.txt
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<code>Dibuat Pada  :</code> <b>$tnggl</b>
<code>Berakhir Pada:</code> <b>$expe</b>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

# function notif transaksi
function notiftrx() {
CHATID="$CHATID2"
KEY="$KEY2"
TIME="$TIME"
URL="$URL2"
TEXT="
◇━━━━━━━━━━━━━━━━━━◇
        <b>TRANSAKSI BERHASIL</b>
◇━━━━━━━━━━━━━━━━━━◇
☘️ » <code>Trx     :</code> <code>SSH WS</code>
☘️ » <code>Pembeli :</code> @${pembeli}
☘️ » <code>Domain  :</code> <code>${domain}</code>
☘️ » <code>ISP     :</code> <code>${ISP}</code>
☘️ » <code>Region  :</code> <code>${CITY}</code>
☘️ » <code>User IP :</code> <code>${iplimit} Perangkat</code>
☘️ » <code>Aktif   :</code> <code>${masaaktif} Hari</code>
◇━━━━━━━━━━━━━━━━━━◇
<i>Notif Transaksi Akun SSH...</i>
"'&reply_markup={"inline_keyboard":[[{"text":"☘️ ORDER","url":"https://t.me/alawivpn"},{"text":"TESTI ☘️","url":"https://t.me/configsantritestimoni"}]]}'
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
clear
notiftelebot
notiftrx
echo ""
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "  SSH / OPENVPN ACCOUNT   " | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Username         : $Login" | tee -a /etc/user-create/user.log
echo -e "Password         : $Pass" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Limit Ip         : ${iplimit} User" | tee -a /etc/user-create/user.log
echo -e "Host             : $domain" | tee -a /etc/user-create/user.log
echo -e "Location         : $CITY" | tee -a /etc/user-create/user.log
echo -e "Port OpenSSH     : 443, 80, 22" | tee -a /etc/user-create/user.log
echo -e "Port DNS         : 443, 53 ,22 " | tee -a /etc/user-create/user.log
echo -e "Port SSH UDP     : 1-65535" | tee -a /etc/user-create/user.log
echo -e "Port Dropbear    : 443, 109" | tee -a /etc/user-create/user.log
echo -e "Port SSH WS      : 80, 8080, 8880, 2082, 2095" | tee -a /etc/user-create/user.log
echo -e "Port SSH SSL WS  : 443" | tee -a /etc/user-create/user.log
echo -e "Port SSL/TLS     : 400-900" | tee -a /etc/user-create/user.log
echo -e "Port OVPN WS SSL : 443" | tee -a /etc/user-create/user.log
echo -e "Port OVPN SSL    : 443" | tee -a /etc/user-create/user.log
echo -e "Port OVPN TCP    : 443, 1194" | tee -a /etc/user-create/user.log
echo -e "Port OVPN UDP    : 2200" | tee -a /etc/user-create/user.log
echo -e "BadVPN UDP       : 7100, 7300, 7300" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "SSH UDP VIRAL : $domain:1-65535@$Login:$Pass"            | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "HTTP COSTUM : $domain:80@$Login:$Pass"                   | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Payload WS       : GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: ws[crlf][crlf]" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "OVPN Download    : https://$domain:81/" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Save Link Account: https://$domain:81/ssh-$Login.txt" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Dibuat Pada      : $tnggl" | tee -a /etc/user-create/user.log
echo -e "Berakhir Pada    : $expe" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log

read -p "Enter Back To Menu"
menu
