#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
NS=$( cat /etc/xray/dns )
PUB=$( cat /etc/slowdns/server.pub )
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
#===================================
#Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
# getting notif trx
CHATID2=$(grep -E "^#bot# " "/etc/bottrx/.bot.db" | cut -d ' ' -f 3)
KEY2=$(grep -E "^#bot# " "/etc/bottrx/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL2="https://api.telegram.org/bot$KEY2/sendMessage"
clear
#===================================
# detail server
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
clear
#===================================
tr="$(cat ~/log-install.txt | grep -w "Trojan WS " | cut -d: -f2|sed 's/ //g')"
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
# // color
grs="\033[1;93m"
bg="\033[42m"
gr="\e[92;1m"
NC='\033[0m'
clear
echo -e ""
echo -e "${grs}┌───────────────────────────────────────────────┐${NC}"
echo -e "${grs}│${bg}               ADD ACCOUNT TROJAN              ${NC}${grs}│${NC}"
echo -e "${grs}└───────────────────────────────────────────────┘${NC}"
echo -e ""
		read -rp "User           : " -e user
		user_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

		if [[ ${user_EXISTS} == '1' ]]; then
clear
    echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
    echo -e "                                         WARNING ❗❗ "
    echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
			echo ""
			echo "Username or Name is Ready !!"
			echo ""
			echo -e "\033[1;93m──────────────────────────────────────────\033[0m"
			read -n 1 -s -r -p "Press any key to back on menu"
			m-trojan
		fi
	done
# perhitungan dan detail
uuid=$(cat /proc/sys/kernel/random/uuid)
while true;do
    read -p "Expired (days) : " masaaktif
    [[ -n "$" ]] && break
done
while true;do
    read -p "Limit User (GB): " Quota
    [[ -n "$Quota" ]] && break
done
while true;do
    read -p "Limit User (IP): " iplimit
    [[ -n "$iplimit" ]] && break
done
while true;do
    read -p "Username Buyer : " pembeli
    [[ -n "$pembeli" ]] && break
done
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

# Link Trojan Akun
systemctl restart xray
cat >/var/www/html/trojan-$user.txt <<-END
----------------------------
      Format For Clash
----------------------------

# Format Trojan GO/WS

- name: Trojan-$user-GO/WS
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}

# Format Trojan gRPC

- name: Trojan-$user-gRPC
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc
END

clear

systemctl reload xray
systemctl reload nginx
service cron restart
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/trojan/ip
echo -e "$iplimit" > /etc/kyt/limit/trojan/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL
clear
echo -e ""
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇"
echo -e "     TROJAN ACCOUNT      " | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇"
echo -e "Remarks          : ${user}"  | tee -a /etc/user-create/user.log
echo -e "Aktif Selama     : $masaaktif Hari" | tee -a /etc/user-create/user.log
echo -e "Dibuat Pada      : $tnggl" | tee -a /etc/user-create/user.log
echo -e "Berakhir Pada    : $expe" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇"
echo -e "Host/IP          : ${domain}" | tee -a /etc/user-create/user.log
echo -e "User Quota       : ${Quota} GB" | tee -a /etc/user-create/user.log
echo -e "User Ip          : ${iplimit} IP" | tee -a /etc/user-create/user.log
echo -e "Port             : 400-900"  | tee -a /etc/user-create/user.log
echo -e "Key              : ${uuid}"  | tee -a /etc/user-create/user.log
echo -e "Path             : /trojan-ws/multi-path" | tee -a /etc/user-create/user.log
echo -e "ServiceName      : trojan-grpc"  | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇"
echo -e "Link TLS         : ${trojanlink}"  | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇"
echo -e "Link GRPC        : ${trojanlink1}"  | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇"
echo -e "Format OpenClash : https://${domain}:81/trojan-$user.txt"  | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇"
echo -e ""
echo ""  | tee -a /etc/user-create/user.log

# Function to send notification to Telegram Bot
function notiftelebot() {
export CHATID="$CHATID"
export KEY="$KEY"
export TIME="$TIME"
export URL="$URL"
export user="${user}"
export masaaktif="$masaaktif"
export tnggl="${tnggl}"
export expe="${expe}"
export domain="${domain}"
export Quota="${Quota}"
export iplimit="${iplimit}"
export uuid="${uuid}"
export trojanlink="${trojanlink}"
export trojanlink1="${trojanlink1}"

python3 - <<END
import os
import requests
# Mendapatkan nilai variabel bash menggunakan os.getenv()
CHATID = os.getenv('CHATID')
KEY = os.getenv('KEY')
TIME = os.getenv('TIME')
URL = os.getenv('URL')
user = os.getenv('user')
masaaktif = os.getenv('masaaktif')
tnggl = os.getenv('tnggl')
expe = os.getenv('expe')
domain = os.getenv('domain')
Quota = os.getenv('Quota')
iplimit = os.getenv('iplimit')
uuid = os.getenv('uuid')
trojanlink = os.getenv('trojanlink')
trojanlink1 = os.getenv('trojanlink1')

# Fungsi untuk mengirim pesan ke bot Telegram
def kirim_pesan(pesan):
    TOKEN = KEY  # Ganti dengan token API bot Telegram Anda
    chat_id = CHATID  # Ganti dengan ID obrolan atau username penerima pesan

    url = f'https://api.telegram.org/bot{TOKEN}/sendMessage'
    params = {
        'chat_id': chat_id,
        'text': pesan,
        'parse_mode': 'HTML'  # Menggunakan HTML untuk formatting teks
    }

    response = requests.post(url, params=params)
    return response.json()
#proses kirim teks/pesan ken bot
pesan = f"""
◇━━━━━━━━━━━━━━━━━━━━━━━◇
     <b>AKUN TROJAN SUKSES DIBUAT</b>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<code>Remarks     :</code> {user}
<code>Host/IP     :</code> {domain}
<code>User Quota  :</code> {Quota} GB
<code>User IP     :</code> {iplimit} IP
<code>Port        :</code> 400-900
<code>Key         :</code> <code>{uuid}</code>
<code>Path        :</code> /trojan-ws/multipath/
<code>ServiceName :</code> trojan-grpc
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>Link WS :</b>
<code>{trojanlink}</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>Link GRPC :</b>
<code>{trojanlink1}</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>Format Open Clash :</b>
https://{domain}:81/trojan-{user}.txt
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<code>Dibuat pada :</code> {tnggl}
<code>Berakhir    :</code> {expe}
◇━━━━━━━━━━━━━━━━━━━━━━━◇
"""
kirim_pesan(pesan)
END
}
# function notif transaksi
function notiftrx() {
CHATID="$CHATID2"
KEY="$KEY2"
TIME="$TIME"
URL="$URL2"
TEXT="
◇━━━━━━━━━━━━━━━━━━◇
        <b>TRANSAKSI BERHASIL</b>
◇━━━━━━━━━━━━━━━━━━◇
☘️ » <code>Trx     :</code> <code>Trojan Account</code>
☘️ » <code>Pembeli :</code> @${pembeli}
☘️ » <code>Domain  :</code> <code>${domain}</code>
☘️ » <code>ISP     :</code> <code>${ISP}</code>
☘️ » <code>Region  :</code> <code>${CITY}</code>
☘️ » <code>User IP :</code> <code>${iplimit} Perangkat</code>
☘️ » <code>Aktif   :</code> <code>${masaaktif} Hari</code>
◇━━━━━━━━━━━━━━━━━━◇
<i>Notif Transaksi Akun Trojan...</i>
"'&reply_markup={"inline_keyboard":[[{"text":"☘️ ORDER","url":"https://t.me/alawivpn"},{"text":"TESTI ☘️","url":"https://t.me/configsantritestimoni"}]]}'
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
notiftelebot
notiftrx
echo -e "TROJAN SDH BERHASIL DIKIRIM KE TELEGRAM"
echo -e ""
read -p "Tekan [ enter ] untuk kembali "
m-trojan
