#!/bin/bash

NC='\e[0m'
#===================================
# Telegram Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
# getting notif trx
CHATID2=$(grep -E "^#bot# " "/etc/bottrx/.bot.db" | cut -d ' ' -f 3)
KEY2=$(grep -E "^#bot# " "/etc/bottrx/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL2="https://api.telegram.org/bot$KEY2/sendMessage"
clear
#===================================
# detail server
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
# // ip info
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
#===================================
# // Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
# // color
grs="\033[1;93m"
bg="\033[42m"
gr="\e[92;1m"
NC='\033[0m'
clear
echo -e ""
echo -e "${grs}┌───────────────────────────────────────────────┐${NC}"
echo -e "${grs}│${bg}                ADD ACCOUNT VLESS              ${NC}${grs}│${NC}"
echo -e "${grs}└───────────────────────────────────────────────┘${NC}"
echo -e ""
while true; do
    read -rp "User          : " -e user
    [[ -n  "$user" ]]; && break
done
  CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
    echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
    echo -e "                                      WARNING ❗❗ "
    echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
			echo ""
			echo "Username or Name is Ready !!"
			echo ""
			echo -e "\033[1;93m──────────────────────────────────────────\033[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
  fi
done
uuid=$(cat /proc/sys/kernel/random/uuid)
while true;do
    read -p "Expired (days) : " masaaktif
    [[ -n "$" ]] && break
done
while true;do
    read -p "Limit User (GB): " Quota
    [[ -n "$Quota" ]] && break
done
while true;do
    read -p "Limit User (IP): " iplimit
    [[ -n "$iplimit" ]] && break
done
while true;do
    read -p "Username Buyer : " pembeli
    [[ -n "$pembeli" ]] && break
done
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/vless/ip
echo -e "$iplimit" > /etc/kyt/limit/vless/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db
clear
cat >/var/www/html/vless-$user.txt <<-END

----------------------------
      Format For Clash
----------------------------
# Format Vless WS TLS

- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}

# Format Vless WS Non TLS

- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

# Format Vless gRPC (SNI)

- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
    grpc-service-name: vless-grpc

----------------------------
Link Akun Vless 
----------------------------
Link TLS      : 
${vlesslink1}
----------------------------
Link none TLS : 
${vlesslink2}
----------------------------
Link GRPC     : 
${vlesslink3}
----------------------------
END

systemctl restart xray
systemctl restart nginx
clear
echo -e ""
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "          VLESS          " | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Remarks       : ${user}" | tee -a /etc/user-create/user.log
echo -e "Aktif Selama  : $masaaktif Hari" | tee -a /etc/user-create/user.log
echo -e "Dibuat Pada   : $tnggl" | tee -a /etc/user-create/user.log
echo -e "Berakhir Pada : $expe" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Domain        : ${domain}" | tee -a /etc/user-create/user.log
echo -e "User Quota    : ${Quota} GB" | tee -a /etc/user-create/user.log
echo -e "User Ip       : ${iplimit} IP" | tee -a /etc/user-create/user.log
echo -e "port TLS      : 400-900" | tee -a /etc/user-create/user.log
echo -e "Port DNS      : 443" | tee -a /etc/user-create/user.log
echo -e "Port NTLS     : 80, 8080, 8880, 2082" | tee -a /etc/user-create/user.log
echo -e "User ID       : ${uuid}" | tee -a /etc/user-create/user.log
echo -e "Encryption    : none" | tee -a /etc/user-create/user.log
echo -e "Path TLS      : /vless/multi-path " | tee -a /etc/user-create/user.log
echo -e "ServiceName   : vless-grpc" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Link TLS      : ${vlesslink1}" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Link NTLS     : ${vlesslink2}" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Link GRPC     : ${vlesslink3}" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Format OpenClash : https://${domain}:81/vless-$user.txt" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e ""
echo "" | tee -a /etc/user-create/user.log

# Function to send notification to Telegram Bot
function notiftelebot() {
export CHATID="$CHATID"
export KEY="$KEY"
export TIME="$TIME"
export URL="$URL"
export user="${user}"
export masaaktif="$masaaktif"
export tnggl="${tnggl}"
export expe="${expe}"
export domain="${domain}"
export Quota="${Quota}"
export iplimit="${iplimit}"
export uuid="${uuid}"
export vlesslink1="${vlesslink1}"
export vlesslink2="${vlesslink2}"
export vlesslink3="${vlesslink3}"

python3 - <<END
import os
import requests
# Mendapatkan nilai variabel bash menggunakan os.getenv()
CHATID = os.getenv('CHATID')
KEY = os.getenv('KEY')
TIME = os.getenv('TIME')
URL = os.getenv('URL')
user = os.getenv('user')
masaaktif = os.getenv('masaaktif')
tnggl = os.getenv('tnggl')
expe = os.getenv('expe')
domain = os.getenv('domain')
Quota = os.getenv('Quota')
iplimit = os.getenv('iplimit')
uuid = os.getenv('uuid')
vlesslink1 = os.getenv('vlesslink1')
vlesslink2 = os.getenv('vlesslink2')
vlesslink3 = os.getenv('vlesslink3')

# Fungsi untuk mengirim pesan ke bot Telegram
def kirim_pesan(pesan):
    TOKEN = KEY  # Ganti dengan token API bot Telegram Anda
    chat_id = CHATID  # Ganti dengan ID obrolan atau username penerima pesan

    url = f'https://api.telegram.org/bot{TOKEN}/sendMessage'
    params = {
        'chat_id': chat_id,
        'text': pesan,
        'parse_mode': 'HTML'  # Menggunakan HTML untuk formatting teks
    }

    response = requests.post(url, params=params)
    return response.json()
#proses kirim teks/pesan ken bot
pesan = f"""
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>     XRAY/VLESS SUCCES CREATED</b>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<code>Remarks       :</code> {user}
<code>Aktif Selama  :</code> {masaaktif} Hari
<code>Dibuat Pada   :</code> {tnggl}
<code>Berakhir Pada :</code> {expe}
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<code>Domain        :</code> <code>{domain}</code>
<code>User Quota    :</code> {Quota} GB
<code>User Ip       :</code> {iplimit} IP
<code>port TLS      :</code> 400-900
<code>Port DNS      :</code> 443
<code>Port NTLS     :</code> 80, 8080, 8880, 2082
<code>User ID       :</code> <code>{uuid}</code>
<code>Encryption    :</code> none
<code>Path TLS      :</code> /vless/multi-path
<code>ServiceName   :</code> vless-grpc
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>Link TLS      :</b>
<code>{vlesslink1}</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>Link NTLS     :</b>
<code>{vlesslink2}</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>Link GRPC     :</b>
<code>{vlesslink3}</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>Format OpenClash :</b>
https://{domain}:81/vless-{user}.txt
◇━━━━━━━━━━━━━━━━━━━━━━━◇
"""
kirim_pesan(pesan)
END
}
# function notif transaksi
function notiftrx() {
CHATID="$CHATID2"
KEY="$KEY2"
TIME="$TIME"
URL="$URL2"
TEXT="
◇━━━━━━━━━━━━━━━━━━◇
        <b>TRANSAKSI BERHASIL</b>
◇━━━━━━━━━━━━━━━━━━◇
☘️ » <code>Trx     :</code> <code>VLESS Account</code>
☘️ » <code>Pembeli :</code> @${pembeli}
☘️ » <code>Domain  :</code> <code>${domain}</code>
☘️ » <code>ISP     :</code> <code>${ISP}</code>
☘️ » <code>Region  :</code> <code>${CITY}</code>
☘️ » <code>User IP :</code> <code>${iplimit} Perangkat</code>
☘️ » <code>Aktif   :</code> <code>${masaaktif} Hari</code>
◇━━━━━━━━━━━━━━━━━━◇
<i>Notif Transaksi Akun VLESS...</i>
"'&reply_markup={"inline_keyboard":[[{"text":"☘️ ORDER","url":"https://t.me/alawivpn"},{"text":"TESTI ☘️","url":"https://t.me/configsantritestimoni"}]]}'
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
notiftelebot
notiftrx
echo -e "SUDAH DIKIRIM KE TELEGRAM"
echo -e ""
read -p "Tekan [ enter ] untuk kembali "
m-vless
