#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
NS=$( cat /etc/xray/dns )
PUB=$( cat /etc/slowdns/server.pub )
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
#===================================
# Getting notif
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
# getting notif trx
CHATID2=$(grep -E "^#bot# " "/etc/bottrx/.bot.db" | cut -d ' ' -f 3)
KEY2=$(grep -E "^#bot# " "/etc/bottrx/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL2="https://api.telegram.org/bot$KEY2/sendMessage"
clear
#===================================
MYIP=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)

#tls="$(cat ~/log-install.txt | grep -w "Vmess TLS" | cut -d: -f2|sed 's/ //g')"
#none="$(cat ~/log-install.txt | grep -w "Vmess None TLS" | cut -d: -f2|sed 's/ //g')"
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
# // color
grs="\033[1;93m"
bg="\033[42m"
gr="\e[92;1m"
NC='\033[0m'
clear
echo -e ""
echo -e "${grs}┌───────────────────────────────────────────────┐${NC}"
echo -e "${grs}│${bg}                ADD ACCOUNT VMESS              ${NC}${grs}│${NC}"
echo -e "${grs}└───────────────────────────────────────────────┘${NC}"
echo -e ""
while true; do
    read -rp "User           : " -e user
    [[ -n "${user}" ]] && break
done
CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
	if [[ ${CLIENT_EXISTS} == '1' ]]; then
		clear
		echo -e "${gr}Username sudah ada... Pakai yang lain!$NC"
		read -n 1 -s -r -p "Kembali tekan [enter] "
		addws
	fi
done
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
uuid=$(cat /proc/sys/kernel/random/uuid)
while true; do
    read -p "Expired (days) : " masaaktif
    [[ -n "${masaaktif}" ]] && break
done
while true; do
    read -p "Limit User (GB): " Quota
    [[ -n "${Quota}" ]] && break
done
while true; do
    read -p "Limit User (IP): " iplimit
    [[ -n "${iplimit}" ]] && break
done
while true; do
    read -p "Username Buyer : " pembeli
    [[ -n "${pembeli}" ]] && break
done
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl-$bln-$thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2-$bln2-$thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json

vmtls=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
vmntls=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF`
vmgrpc=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-grpc",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
vmess_base641=$( base64 -w 0 <<< $vmess_json1)
vmess_base642=$( base64 -w 0 <<< $vmess_json2)
vmess_base643=$( base64 -w 0 <<< $vmess_json3)
vmesslink1="vmess://$(echo $vmtls | base64 -w 0)"
vmesslink2="vmess://$(echo $vmntls | base64 -w 0)"
vmesslink3="vmess://$(echo $vmgrpc | base64 -w 0)"
systemctl restart xray > /dev/null 2>&1
service cron restart > /dev/null 2>&1


cat >/var/www/html/vmess-$user.txt <<-END

----------------------------
      Format For Clash
----------------------------

# Format Vmess WS TLS

- name: Vmess-$user-WS TLS
  type: vmess
  server: ${domain}
  port: 443
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess WS Non TLS

- name: Vmess-$user-WS Non TLS
  type: vmess
  server: ${domain}
  port: 80
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess gRPC

- name: Vmess-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vmess
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  network: grpc
  tls: true
  servername: ${domain}
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: vmess-grpc

----------------------------
 Link Akun Vmess
----------------------------
Link TLS         :
${vmesslink1}
----------------------------
Link none TLS    :
${vmesslink2}
----------------------------
Link GRPC        :
${vmesslink3}
----------------------------

END
if [ ! -e /etc/vmess ]; then
  mkdir -p /etc/vmess
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/vmess/ip
echo -e "$iplimit" > /etc/kyt/limit/vmess/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vmess/${user}
fi
DATADB=$(cat /etc/vmess/.vmess.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vmess/.vmess.db
fi
echo "### $user $Quota $iplimit $uuid $masaaktif $tnggl $expe" >>/etc/vmess/.vmess.db
clear
# Function to send notification to Telegram Bot
function notiftelebot() {
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>     XRAY/VMESS SUCCES CREATED</b>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<code>Remarks   : ${user}
Domain    : ${domain}
Quota     : ${Quota} GB
User Ip   : ${iplimit} IP
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : ${uuid}
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : vmess-grpc</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>VMESS WS TLS :</b>
<code>${vmesslink1}</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>VMESS WS NO TLS :</b>
<code>${vmesslink2}</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>VMESS gRPC :</b>
<code>${vmesslink3}</code>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b>Format OpenClash :</b>
https://${domain}:81/vmess-$user.txt
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<code>Aktif Selama   :</code> ${masaaktif}
<code>Dibuat Pada    :</code> ${tnggl}
<code>Berakhir Pada  :</code> ${expe}
◇━━━━━━━━━━━━━━━━━━━━━━━◇
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
# function notif transaksi
function notiftrx() {
CHATID="$CHATID2"
KEY="$KEY2"
TIME="$TIME"
URL="$URL2"
TEXT="
◇━━━━━━━━━━━━━━━━━━◇
        <b>TRANSAKSI BERHASIL</b>
◇━━━━━━━━━━━━━━━━━━◇
☘️ » <code>Trx     :</code> <code>VMESS Account</code>
☘️ » <code>Pembeli :</code> @${pembeli}
☘️ » <code>Domain  :</code> <code>${domain}</code>
☘️ » <code>ISP     :</code> <code>${ISP}</code>
☘️ » <code>Region  :</code> <code>${CITY}</code>
☘️ » <code>User IP :</code> <code>${iplimit} Perangkat</code>
☘️ » <code>Aktif   :</code> <code>${masaaktif} Hari</code>
◇━━━━━━━━━━━━━━━━━━◇
<i>Notif Transaksi Akun VMESS...</i>
"'&reply_markup={"inline_keyboard":[[{"text":"☘️ ORDER","url":"https://t.me/alawivpn"},{"text":"TESTI ☘️","url":"https://t.me/configsantritestimoni"}]]}'
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
clear
notiftelebot
notiftrx
clear
echo -e "VMESS SDH BERHASIL DIKIRIM KE TELEGRAM"
clear
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e " VMESS ACCOUNT " | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Remarks          : ${user}" | tee -a /etc/user-create/user.log
echo -e "Aktif Selama     : $masaaktif Hari" | tee -a /etc/user-create/user.log
echo -e "Dibuat Pada      : $tnggl" | tee -a /etc/user-create/user.log
echo -e "Berakhir Pada    : $expe" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Domain           : ${domain}" | tee -a /etc/user-create/user.log
echo -e "User Quota       : ${Quota} GB"  | tee -a /etc/user-create/user.log
echo -e "User Ip          : ${iplimit} IP" | tee -a /etc/user-create/user.log
echo -e "Port TLS         : 400-900" | tee -a /etc/user-create/user.log
echo -e "Port none TLS    : 80, 8080, 8880, 2082" | tee -a /etc/user-create/user.log
echo -e "id               : ${uuid}" | tee -a /etc/user-create/user.log
echo -e "alterId          : 0" | tee -a /etc/user-create/user.log
echo -e "Security         : auto" | tee -a /etc/user-create/user.log
echo -e "Network          : ws" | tee -a /etc/user-create/user.log
echo -e "Path             : /vmess/multi-path" | tee -a /etc/user-create/user.log
echo -e "Dynamic          : https://bugmu.com/path" | tee -a /etc/user-create/user.log
echo -e "ServiceName      : vmess-grpc" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Link TLS         : ${vmesslink1}" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Link none TLS    : ${vmesslink2}" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Link GRPC        : ${vmesslink3}" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e "Format OpenClash : https://${domain}:81/vmess-$user.txt" | tee -a /etc/user-create/user.log
echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a /etc/user-create/user.log
echo -e ""
echo "" | tee -a /etc/user-create/user.log
read -p "Tekan [ enter ] untuk kembali "
m-vmess
