#!/bin/bash
# ==========================================
# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
IP=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
date=$(date +"%Y-%m-%d")
email=$(cat /etc/xray/email)
if [[ "$email" = "" ]]; then
echo -e ""
clear
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;92m               INPUT YOUR EMAIL\033[0m"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -rp "Email : " -e email
cat <<EOF>>/etc/xray/email
$email
EOF
fi
clear
echo -e ""
echo -e ""
echo -e ""
echo -e "Wait , Backup Procces...................." | lolcat
cd
rm -rf /root/backup
mkdir /root/backup
cp /etc/passwd backup/
cp /etc/group backup/
cp /etc/shadow backup/
cp /etc/gshadow backup/
cp /etc/crontab backup/
cp -r /var/lib/kyt/ backup/kyt
cp -r /etc/xray backup/xray
cp -r /etc/bot backup/bot
cp -r /etc/bottrx backup/bottrx
cp -r /var/www/html/ backup/html
cd /root
zip -r $IP-$date.zip backup > /dev/null 2>&1
rclone copy /root/$IP-$date.zip dr:backup/
url=$(rclone link dr:backup/$IP-$date.zip)
id=(`echo $url | grep '^https' | cut -d'=' -f2`)
link="https://drive.google.com/u/4/uc?id=${id}&export=download"
echo -e "
Detail Backup
==================================
IP VPS        : $IP
Link Backup   : $link
Tanggal       : $date
==================================
" | mail -s "Backup Data" $email
rm -rf /root/backup
rm -r /root/$IP-$date.zip

clear
echo -e "
Detail Backup
==================================
IP VPS        : $IP
Link Backup   : $link
Tanggal       : $date
==================================
"
echo "Silahkan copy Link dan restore di VPS baru"
echo ""
function notiftelebot() {
export CHATID="$CHATID"
export KEY="$KEY"
export TIME="$TIME"
export URL="$URL"
export IP="$IP"
export domain="$domain"
export link2="$link"
export date="$date"

python3 - <<END
import os
import requests
# Mendapatkan nilai variabel bash menggunakan os.getenv()
CHATID = os.getenv('CHATID')
KEY = os.getenv('KEY')
TIME = os.getenv('TIME')
URL = os.getenv('URL')
IP = os.getenv('IP')
domain = os.getenv('domain')
link = os.getenv('link2')
date = os.getenv('date')

# Fungsi untuk mengirim pesan ke bot Telegram
def kirim_pesan(pesan):
    TOKEN = KEY  # Ganti dengan token API bot Telegram Anda
    chat_id = CHATID  # Ganti dengan ID obrolan atau username penerima pesan

    url = f'https://api.telegram.org/bot{TOKEN}/sendMessage'
    params = {
        'chat_id': chat_id,
        'text': pesan,
        'parse_mode': 'HTML'  # Menggunakan HTML untuk formatting teks
    }

    response = requests.post(url, params=params)
    return response.json()
#proses kirim teks/pesan ken bot
pesan = f"""
────────────────────
<b>☘ BERHASIL BACKUP VPS ☘</b>
────────────────────
<code>IP VPS  :</code> <code>{IP}</code>
<code>Domain  :</code> <code>{domain}</code>
<code>Tanggal :</code> <code>{date}</code>
────────────────────
<b>Link Backup:</b>
<code>{link}</code>
────────────────────
<i>Silahkan copy Link dan restore di VPS baru</i>
"""
kirim_pesan(pesan)
END
}
notiftelebot
