#!/bin/bash
grs='\e[0;93m'
gr='\e[1;32m'
red='\e[0;31m'
bg='\e[0;42'
NC='\e[0m'
clear
# function checking vps
cekvps() {
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "${gr}Memeriksa izin...${NC}"
IZIN=$(curl -sS https://raw.githubusercontent.com/petapaan/labang/main/bangkalan | grep $MYIP | awk '{print $4}')
if [[ "$MYIP" == "$IZIN" ]]; then
    echo -e "${gr}Sudah terdaftar dalam perizinan...${NC}"
else
    bash dilarang
    exit 0
fi
}
cekvps
clear
echo -e ""
echo -e " ${grs}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "      ${gr}MENU TAMBAHKAN BOT NOTIF & TRANSAKSI${NC}"
echo -e " ${grs}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "                       |"
echo -e " [${gr}01${NC}] ADD BOT NOTIF${NC}    | [${gr}03${NC}] DELETE BOT NOTIF${NC}"
echo -e "                       |"
echo -e " [${gr}02${NC}] ADD BOT TRX${NC}      | [${gr}04${NC}] DELETE BOT TRX${NC}"
echo -e "                       |"
echo -e " ${grs}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "              [${gr}00${NC}] KEMBALI KE MENU${NC}"
echo -e " ${grs}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

read -rp "$(echo -e " Silahkan pilih ${gr}1${NC}-${gr}4${NC} atau ${gr}0${NC}: ")" menu
case $menu in
    1) clear ; add-bot-notif ;;
    2) clear ; add-bot-trx ;;
    3) clear ; del-bot-notif ;;
    4) clear ; del-bot-trx ;;
    0) clear ; menu ;;
    *) clear ; menu ;;
esac
