#!/bin/bash
GREEN="\e[1;32m"
NC="\e[0m"
# Fungsi untuk menghapus log
clear_log() {
    log=$1
    if [ -f "$log" ]; then
        echo > "$log"
    fi
}

# Pencarian dan penghapusan log
data=( $(find /var/log/ -name "*.log") )
echo -e "${GREEN}Clearing Log...${NC}"
for log in "${data[@]}"; do
    clear_log "$log"
    echo -e "${GREEN}Log${NC} - $log - ${GREEN}Berhasil dihapus!${NC}"
done

# Penghapusan log tambahan
logs_to_clear=(
    "/var/log/syslog"
    "/var/log/btmp"
    "/var/log/messages"
    "/var/log/debug"
)

for log in "${logs_to_clear[@]}"; do
    clear_log "$log"
    echo -e "${GREEN}Log${NC} - $log - ${GREEN}Berhasil dihapus!${NC}"
done

# Membersihkan cache
echo -e "${GREEN}Clearing Cache...${NC}"
if [ "$(command -v apt-get)" ]; then
    apt-get clean
elif [ "$(command -v yum)" ]; then
    yum clean all
fi

echo -e "Cache - ${GREEN}Berhasil dihapus!${NC}"
echo ""
