#!/bin/bash
# ==========================================
# Color
RED='\033[1;31m'
NC='\033[0m'
GREEN='\033[1;32m'
ORANGE='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
LIGHT='\033[1;37m'
clear
#Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
# ==========================================
NUMBER_OF_CLIENTS=$(grep -c -E "#ssh# " "/etc/ssh/.ssh.db")
if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
  echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
  echo -e "\e[1;97;101m            CONFIG SSH ACCOUNT            \E[0m"
  echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
  echo ""
  echo "You have no existing clients!"
  read -rp "Tekan enter untuk kembali"
  m-sshws
fi

echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\e[1;97;101m        DELETE CONFIG SSH ACCOUNT         \E[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
printf "%-5s%-13s%-13s%s\n" "No" "User" "Pass" "Expired"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
grep -E "#ssh# " "/etc/ssh/.ssh.db" | cut -d ' ' -f 2-8 | nl -s ') ' | awk -v OFS="\t" '{ printf "%-5s%-13s%-13s%s\n", $1, $2, $3, $8 }'
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
  if [[ ${CLIENT_NUMBER} == '1' ]]; then
    read -rp "Select one client [1]: " CLIENT_NUMBER
  else
    read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
  fi
done

user=$(grep -E "#ssh# " "/etc/ssh/.ssh.db" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)

# hapus di .ssh.db
file=/etc/ssh/.ssh.db
file2=/etc/passwd
file3=/etc/shadow
sed -i "/$user/d" $file
sed -i "/$user/d" $file2
sed -i "/$user/d" $file3
echo -e "${GREEN}User ${ORANGE}$user ${GREEN}Berhasil ${RED}Dihapus ${GREEN}Sayang.${NC}"
# kirim notifikasi ke bot telegram
function notiftelebot() {
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
◇━━━━━━━━━━━━━━━━━━━━━━━◇
       <b>AKUN SSH SUKSES DIHAPUS</b>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<code>Nama    :</code> <b>$user</b>
◇━━━━━━━━━━━━━━━━━━━━━━━◇
<b><i>Notifikasi otomatis dari server...</i></b>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
notiftelebot
echo -e ""
echo -e "NOTIF ${GREEN}BERHASIL ${NC}DIKIRIM KE TELEGRAM"
echo -e ""
read -p "Tekan [ enter ] untuk kembali "
m-sshws
