#!/bin/bash
# // color
grs="\033[1;93m"
bg="\033[42m"
gr="\e[92;1m"
cy="\033[1;93m"
#cy="\033[1;36m"
NC='\033[0m'
clear
if [ -e "/var/log/auth.log" ]; then
    LOG="/var/log/auth.log"
fi

if [ -e "/var/log/secure" ]; then
    LOG="/var/log/secure"
fi

data=( $(ps aux | grep -i dropbear | awk '{print $2}') )
cek_beserta_ip(){
echo -e "$cy====================================$NC"
echo -e "$(printf "${gr}%-20s ${cy}%-5s ${gr}%-10s %s\n" "USER" "|" "IP")"
echo -e "$cy====================================$NC"
cat "$LOG" | grep -i dropbear | grep -i "Password auth succeeded" > /tmp/login-db.txt
total_pid=0
declare -A user_counts
while IFS= read -r line
do
    PID=$(echo "$line" | awk '{print $6}' | cut -d "[" -f2)
    USER=$(echo "$line" | awk '{print $10}' | sed "s/'//g")
    IP=$(echo "$line" | awk '{print $12}')
    printf "${gr}%-20s ${cy}%-5s ${gr}%-10s %s\n" "$USER" "|" "$IP"
    #printf "%-10s %s\n" "$USER" "$IP"
    ((total_pid++))
    if [[ -v user_counts["$USER"] ]]; then
        ((user_counts["$USER"]++))
    else
        user_counts["$USER"]=1
    fi
done < <(grep "dropbear\[" /tmp/login-db.txt)

echo -e "$cy====================================$NC"
echo -e "$(printf "${gr}%-20s ${cy}%-5s ${gr}%-10s %s\n" "USER" "|" "LOGIN")"
echo -e "$cy====================================$NC"
for user in "${!user_counts[@]}"; do
    count=${user_counts["$user"]}
    printf "${gr}%-20s ${cy}%-5s ${gr}%-10s %s\n" "$user" "|" "$count"
done
echo -e "$cy====================================$NC"
printf "${gr}%-20s ${cy}%-5s ${gr}%-10s %s\n" "Total" "|" "$total_pid"
echo -e "$cy====================================$NC"
}

# function di sini saja
ini_saja() {

cat "$LOG" | grep -i dropbear | grep -i "Password auth succeeded" > /tmp/login-db.txt
total_pid=0
declare -A user_counts
while IFS= read -r line
do
    PID=$(echo "$line" | awk '{print $6}' | cut -d "[" -f2)
    USER=$(echo "$line" | awk '{print $10}' | sed "s/'//g")
    IP=$(echo "$line" | awk '{print $12}')
    #printf "${gr}%-20s ${cy}%-5s ${gr}%-10s %s\n" "$USER" "|" "$IP"
    #printf "%-10s %s\n" "$USER" "$IP"
    ((total_pid++))
    if [[ -v user_counts["$USER"] ]]; then
        ((user_counts["$USER"]++))
    else
        user_counts["$USER"]=1
    fi
done < <(grep "dropbear\[" /tmp/login-db.txt)

echo -e "$cy====================================$NC"
echo -e "$(printf "${gr}%-20s ${cy}%-5s ${gr}%-10s %s\n" "USER" "|" "LOGIN")"
echo -e "$cy====================================$NC"
for user in "${!user_counts[@]}"; do
    count=${user_counts["$user"]}
    printf "${gr}%-20s ${cy}%-5s ${gr}%-10s %s\n" "$user" "|" "$count"
done
echo -e "$cy====================================$NC"
printf "${gr}%-20s ${cy}%-5s ${gr}%-10s %s\n" "Total" "|" "$total_pid"
echo -e "$cy====================================$NC"
}
echo -e ""
read -rp "Cek beserta IP Loginnya (y/n) : " opt
echo -e ""

    if [ "$opt" == "y" ]; then
        cek_beserta_ip
    elif [ "$opt" == "n" ]; then
        ini_saja
    else
        ini_saja
    fi
