#!/bin/bash
grs='\e[0;93m'
gr='\e[1;32m'
red='\e[0;31m'
bg='\e[0;42'
NC='\e[0m'
clear
REPO=$(cat /etc/xray/repo)

# function checking vps
cekvps() {
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "${gr}Memeriksa izin...${NC}"
IZIN=$(curl -sS ${REPO}/bangkalan | grep $MYIP | awk '{print $4}')
if [[ "$MYIP" == "$IZIN" ]]; then
    echo -e "${gr}Sudah terdaftar dalam perizinan...${NC}"
else
    bash dilarang
    exit 0
fi
}
cekvps
clear
echo -e ""
echo -e " ${grs}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " ${gr}              MENU TAMBAHKAN BOT${NC}"
echo -e " ${grs}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
#echo -e ""
echo -e " [${gr}01${NC}] ADD BOT PANEL CREATE ACCOUNTS"
echo -e ""
echo -e " [${gr}02${NC}] ADD BOT NOTIF CREATED & TRX"
echo -e ""
echo -e " [${gr}03${NC}] ADD BOT BACKUP VPS TO TELEGRAM"
echo -e ""
echo -e " [${gr}00${NC}] BACK TO MAIN MENU"
echo -e " ${grs}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
read -rp "$(echo -e " Silahkan pilih ${gr}1${NC}-${gr}3${NC} atau ${gr}0${NC}: ")" menu

1) clear ; mbot-panel ;;
2) clear ; mbot-notif ;;
3) clear ; mbot-backup ;;
0) menu ;;
*) m-bot ;;
esac
