#!/bin/bash
# color
grs="\033[1;93m"
bg="\033[42m"
gr="\e[92;1m"
NC='\033[0m'
clear
# // color
grs="\033[1;93m"
bg="\033[42m"
gr="\e[92;1m"
red='\033[0;31m'
cyn='\033[0;36m'
NC='\033[0m'
clear
# function checking vps
cekvps() {
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "${gr}Memeriksa izin...${NC}"
IZIN=$(curl -sS https://raw.githubusercontent.com/petapaan/labang/main/bangkalan | grep $MYIP | awk '{print $4}')
if [[ "$MYIP" == "$IZIN" ]]; then
    echo -e "${gr}Sudah terdaftar dalam perizinan...${NC}"
else
    bash dilarang
    exit 0
fi
}
cekvps
clear
echo -e ""
echo -e "${grs}┌─────────────────────────────────────────────────┐${NC}"
echo -e "${grs}│${bg}               MENU MANAGER SHDWSKS              ${NC}${grs}│${NC}"
echo -e "${grs}└─────────────────────────────────────────────────┘${NC}"
echo -e "${grs}┌───────────────────────┐ ┌───────────────────────┐${NC}"
echo -e "${grs}│ [${gr}01${NC}] • ADD AKUN       ${grs}│ │ [${gr}04${NC}] • DELETE AKUN    ${grs}│${NC}"
echo -e "${grs}│                       │ │                   ${NC}    │${NC}"
echo -e "${grs}│ [${gr}02${NC}] • TRIAL AKUN     ${grs}│ │ [${gr}05${NC}] • USER ONLINE    ${grs}│${NC}"
echo -e "${grs}│                       │ │                       │${NC}"
echo -e "${grs}│ [${gr}03${NC}] • RENEW AKUN     ${grs}│ │ [${gr}06${NC}] • USER CONFIG    ${grs}│${NC}"
echo -e "${grs}└───────────────────────┘ └───────────────────────┘${NC}"
echo -e "${grs}┌─────────────────────────────────────────────────┐${NC}"
echo -e "${grs}│                [${gr}00${NC}] BACK TO MENU                ${grs}│${NC}"
echo -e "${grs}└─────────────────────────────────────────────────┘${NC}"
echo -e ""
read -p "$(echo -e "Select From Options [ ${gr}1${NC} - ${gr}6${NC} or ${gr}0${NC} ] : ")" menu
echo -e ""
case $menu in
    1|01) addss ;;
    2|02) trialss ;;
    3|03) renewss ;;
    4|04) delss ;;
    5|05) cekss ;;
    6|06) user-ss ;;
    0|00) menu ;;
    *) m-ssws ;;
esac
