#!/bin/bash
clear
# // color
grs="\033[1;93m"
bg="\033[42m"
gr="\e[92;1m"
NC='\033[0m'

red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/petapaan/labang/main/bangkalan"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281524266702"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit 0
  fi
}
clear
echo -e ""
echo -e "${grs} ───────────────────────────────────────${NC}"
echo -e " ${bg}     MENU MANAGER BACKUP & RESTORE     ${NC}"
echo -e "${grs} ───────────────────────────────────────${NC}"
echo -e " [${gr}01${NC}] Backup  (${gr}menu${NC})"
echo -e " [${gr}02${NC}] Restore (${gr}menu${NC})"
echo -e " [${gr}03${NC}] Kembali ke menu"
echo -e "${grs} ───────────────────────────────────────${NC}"
echo -e ""
read -p "$(echo -e " Silahkan pilih ${gr}1${NC}-${gr}3${NC}: ")" opt
echo -e   ""
case $opt in
01 | 1) clear ; backup ;;
02 | 2) clear ; restore ;;
00 | 0) clear ; menu ;;
*) clear ; menu-backup ;;
esac
