#!/bin/bash
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
IP=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
date=$(date +"%Y-%m-%d")
# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
function notif_restore() {
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
━━━━━━━━━━━━━━━━━━━━━
<b>  ☘️ BERHASIL RESTORE VPS ☘️</b>
━━━━━━━━━━━━━━━━━━━━━
<code>Domain  :</code> <code>$domain</code>
<code>IP VPS  :</code> <code>$IP</code>
<code>Tanggal :</code> <code>$date</code>
<code>Proses  :</code> <code>Restore VPS</code>
━━━━━━━━━━━━━━━━━━━━━
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
# ==========================================
# Getting
clear
echo "Silahkan Masukin Link Backupnya"
read -rp "Link File: " -e url
wget -O backup.zip "$url"
unzip backup.zip
rm -f backup.zip
sleep 1
clear
echo Start Restore
cd /root/backup
cp -r bot /etc/
cp -r bottrx /etc/
cd
rm -rf /root/backup
rm -rf backup.zip
# ulangi lagi
wget -O backup.zip "$url"
unzip backup.zip
rm -f backup.zip
clear
cd /root/backup
cp passwd /etc/
cp group /etc/
cp shadow /etc/
cp gshadow /etc/
cp -r kyt /var/lib/
cp -r xray /etc/
cp -r bot /etc/
cp -r bottrx /etc/
cp -r html /var/www/
cp crontab /etc/
clear
notif_restore
cd
rm -rf /root/backup
rm -rf backup.zip
echo -e "Berhasil restore vps"
read -rp "Tekan [ enter ] untuk kembali ke menu"
menu
